import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Nunito } from "next/font/google";
import Header from "@/components/Header";
import ContextProvider from "@/Providers/ContextProvider";

const  nunito=Nunito({
  subsets:["latin"],
  weight:["300","400","500","600","700"],
  variable:"--font-nunito"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <ClerkProvider>
      <ContextProvider>
        
      <body
        className={`${nunito.variable} antialiased`}
      >
    <Header/>
    <main className="py-8 mx-[5rem] xl:mx-[15rem] h-full">
        {children}
        </main>
      </body>
      </ContextProvider>

      </ClerkProvider>
    </html>
  );
}
